### PR TITLE
use pip to install flask-ipywidgets

### PR DESCRIPTION
**Pull request by jf---**

### CODE REVIEW

**Comment by maartenbreddels** [comment]
I see this is attacking #5 , maybe it is good to have better titles for PR's :)
I don't think the .travis.yaml file is in the right location, but let me enable travis!

**Comment by jf---** [comment]
Thx Maarten and duly noted on the branch names.

**Comment by jf---** [comment]
Inching closer... running into some issue running chrome headless on `TravisCI` hope to resolve those by tomorrow... passes a trivial test locally... 

I expect something mergeable will follow shortly

**Comment by jf---** [comment]
> I expect something mergeable will follow shortly

a little late but nonetheless... 
see the fresh PR

**Pull request closed without merging**
